---
- name: Install Chocolatey Packages
  win_chocolatey:
    name: "{{ item }}"
    state: "{{ 'latest' if chocolatey_latest else 'present' }}"
  loop: "{{ [
    chocolatey_packages_basic,
    chocolatey_packages_dev,
    chocolatey_packages_custom,
  ] | flatten(levels=1) }}"
